# Generated by Django 6.1 on 2026-08-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(default='fa-solid fa-seedling', help_text='FontAwesome icon class', max_length=100)),
                ('description', models.TextField()),
                ('link_text', models.CharField(default='Learn More', max_length=100)),
                ('link_url', models.CharField(default='/contact/', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Malik Dhakki Dates Nursery', max_length=200)),
                ('phone_number', models.CharField(default='+923394027665', max_length=50)),
                ('whatsapp_number', models.CharField(default='923469892120', max_length=50)),
                ('email', models.EmailField(default='malik.dhakki.dates.nursery@gmail.com', max_length=254)),
                ('address', models.CharField(default='Main chashma road Dhakki D.I.Khan, KPK, Pakistan', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/itsdhakkidates')),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('youtube_url', models.URLField(blank=True, default='#')),
                ('tiktok_url', models.URLField(blank=True, default='#')),
                ('years_of_farming', models.CharField(default='30+', max_length=20)),
                ('happy_customers', models.CharField(default='250+', max_length=20)),
                ('export_cities', models.CharField(default='50+', max_length=20)),
                ('organic_percentage', models.CharField(default='100%', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
